# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainform.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(484, 437)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BonehorizontalLayout = QtWidgets.QHBoxLayout()
        self.BonehorizontalLayout.setObjectName("BonehorizontalLayout")
        self.BoneROIlabel = QtWidgets.QLabel(MainForm)
        self.BoneROIlabel.setObjectName("BoneROIlabel")
        self.BonehorizontalLayout.addWidget(self.BoneROIlabel)
        self.BoneROIcomboBox = OrsObjectClassComboBox(MainForm)
        self.BoneROIcomboBox.setObjectName("BoneROIcomboBox")
        self.BonehorizontalLayout.addWidget(self.BoneROIcomboBox)
        self.verticalLayout.addLayout(self.BonehorizontalLayout)
        self.CorticalhorizontalLayout = QtWidgets.QHBoxLayout()
        self.CorticalhorizontalLayout.setObjectName("CorticalhorizontalLayout")
        self.CorticalROIlabel = QtWidgets.QLabel(MainForm)
        self.CorticalROIlabel.setObjectName("CorticalROIlabel")
        self.CorticalhorizontalLayout.addWidget(self.CorticalROIlabel)
        self.CorticalROIcomboBox = OrsObjectClassComboBox(MainForm)
        self.CorticalROIcomboBox.setObjectName("CorticalROIcomboBox")
        self.CorticalhorizontalLayout.addWidget(self.CorticalROIcomboBox)
        self.verticalLayout.addLayout(self.CorticalhorizontalLayout)
        self.MarrowhorizontalLayout = QtWidgets.QHBoxLayout()
        self.MarrowhorizontalLayout.setObjectName("MarrowhorizontalLayout")
        self.MarrowROIlabel = QtWidgets.QLabel(MainForm)
        self.MarrowROIlabel.setObjectName("MarrowROIlabel")
        self.MarrowhorizontalLayout.addWidget(self.MarrowROIlabel)
        self.MarrowROIcomboBox = OrsObjectClassComboBox(MainForm)
        self.MarrowROIcomboBox.setObjectName("MarrowROIcomboBox")
        self.MarrowhorizontalLayout.addWidget(self.MarrowROIcomboBox)
        self.verticalLayout.addLayout(self.MarrowhorizontalLayout)
        self.checkBox_calcBoneQuadrentProps = QtWidgets.QCheckBox(MainForm)
        self.checkBox_calcBoneQuadrentProps.setObjectName("checkBox_calcBoneQuadrentProps")
        self.verticalLayout.addWidget(self.checkBox_calcBoneQuadrentProps)
        self.label_2 = QtWidgets.QLabel(MainForm)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(MainForm)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.checkBox_calcMarrowProps = QtWidgets.QCheckBox(MainForm)
        self.checkBox_calcMarrowProps.setObjectName("checkBox_calcMarrowProps")
        self.verticalLayout.addWidget(self.checkBox_calcMarrowProps)
        self.label_5 = QtWidgets.QLabel(MainForm)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.checkBox_calcCorticalSliceProps = QtWidgets.QCheckBox(MainForm)
        self.checkBox_calcCorticalSliceProps.setObjectName("checkBox_calcCorticalSliceProps")
        self.verticalLayout.addWidget(self.checkBox_calcCorticalSliceProps)
        self.label_6 = QtWidgets.QLabel(MainForm)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(MainForm)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(MainForm)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(MainForm)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(MainForm)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MainForm)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.zSlicePadding_spinBox = QtWidgets.QSpinBox(MainForm)
        self.zSlicePadding_spinBox.setMaximum(250)
        self.zSlicePadding_spinBox.setObjectName("zSlicePadding_spinBox")
        self.horizontalLayout.addWidget(self.zSlicePadding_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.OutputFolderhorizontalLayout = QtWidgets.QHBoxLayout()
        self.OutputFolderhorizontalLayout.setObjectName("OutputFolderhorizontalLayout")
        self.OutputFolderlabel = QtWidgets.QLabel(MainForm)
        self.OutputFolderlabel.setObjectName("OutputFolderlabel")
        self.OutputFolderhorizontalLayout.addWidget(self.OutputFolderlabel)
        self.OutputFolderlineEdit = QtWidgets.QLineEdit(MainForm)
        self.OutputFolderlineEdit.setObjectName("OutputFolderlineEdit")
        self.OutputFolderhorizontalLayout.addWidget(self.OutputFolderlineEdit)
        self.toolButton_OutputFolder = QtWidgets.QToolButton(MainForm)
        self.toolButton_OutputFolder.setObjectName("toolButton_OutputFolder")
        self.OutputFolderhorizontalLayout.addWidget(self.toolButton_OutputFolder)
        self.verticalLayout.addLayout(self.OutputFolderhorizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.ComputeverticalLayout = QtWidgets.QVBoxLayout()
        self.ComputeverticalLayout.setObjectName("ComputeverticalLayout")
        self.ComputepushButton = QtWidgets.QPushButton(MainForm)
        self.ComputepushButton.setCheckable(True)
        self.ComputepushButton.setObjectName("ComputepushButton")
        self.ComputeverticalLayout.addWidget(self.ComputepushButton)
        self.verticalLayout.addLayout(self.ComputeverticalLayout)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Form"))
        self.BoneROIlabel.setText(_translate("MainForm", "Bone ROI:"))
        self.CorticalROIlabel.setText(_translate("MainForm", "Cortical ROI:"))
        self.MarrowROIlabel.setText(_translate("MainForm", "Marrow ROI:"))
        self.checkBox_calcBoneQuadrentProps.setText(_translate("MainForm", "Calculate 3D Bone Quadrent Properties"))
        self.label_2.setText(_translate("MainForm", "                                    - Trab.BFV, Trab.th"))
        self.label_3.setText(_translate("MainForm", "                                   - Cort.BVF, Cort.Thickness"))
        self.checkBox_calcMarrowProps.setText(_translate("MainForm", "Calculate 3D Marrow Spacing Properties"))
        self.label_5.setText(_translate("MainForm", "                                    - Trab.Sp"))
        self.checkBox_calcCorticalSliceProps.setText(_translate("MainForm", "Calculate 2D Properties"))
        self.label_6.setText(_translate("MainForm", "                                    - Tt.Ar, Ct.Ar, Ma.Ar"))
        self.label_7.setText(_translate("MainForm", "                                    - Geometric Centroids: Cortex, Periosteal, Endocortical Surface"))
        self.label_8.setText(_translate("MainForm", "                                    - Ct.th"))
        self.label_9.setText(_translate("MainForm", "                                    - Cort.BVF, Trab.BVF"))
        self.label_10.setText(_translate("MainForm", "                                    - Ixx, Iyy, Ixy, Imin, Imax, IPolar"))
        self.label.setText(_translate("MainForm", "Enter the amount of z-slice padding:"))
        self.OutputFolderlabel.setText(_translate("MainForm", "Output Folder:"))
        self.toolButton_OutputFolder.setText(_translate("MainForm", "..."))
        self.ComputepushButton.setText(_translate("MainForm", "Compute"))

from ORSServiceClass.ORSWidget.orsobjectclasscombobox.orsobjectclasscombobox import OrsObjectClassComboBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainForm = QtWidgets.QWidget()
    ui = Ui_MainForm()
    ui.setupUi(MainForm)
    MainForm.show()
    sys.exit(app.exec_())

