# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainform.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.setEnabled(True)
        MainForm.resize(469, 644)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(MainForm)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_ROItoCompare = OrsObjectClassComboBox(MainForm)
        self.comboBox_ROItoCompare.setEditable(False)
        self.comboBox_ROItoCompare.setCurrentText("")
        self.comboBox_ROItoCompare.setObjectName("comboBox_ROItoCompare")
        self.horizontalLayout_2.addWidget(self.comboBox_ROItoCompare)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MainForm)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_GoldStandardROI = OrsObjectClassComboBox(MainForm)
        self.comboBox_GoldStandardROI.setObjectName("comboBox_GoldStandardROI")
        self.horizontalLayout.addWidget(self.comboBox_GoldStandardROI)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(MainForm)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_FileName = QtWidgets.QLineEdit(MainForm)
        self.lineEdit_FileName.setReadOnly(True)
        self.lineEdit_FileName.setObjectName("lineEdit_FileName")
        self.horizontalLayout_3.addWidget(self.lineEdit_FileName)
        self.toolButton_OpenFileBrowser = QtWidgets.QToolButton(MainForm)
        self.toolButton_OpenFileBrowser.setObjectName("toolButton_OpenFileBrowser")
        self.horizontalLayout_3.addWidget(self.toolButton_OpenFileBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox_Results = QtWidgets.QGroupBox(MainForm)
        self.groupBox_Results.setObjectName("groupBox_Results")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Results)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_valueTP = QtWidgets.QLineEdit(self.groupBox_Results)
        self.lineEdit_valueTP.setEnabled(True)
        self.lineEdit_valueTP.setToolTip("")
        self.lineEdit_valueTP.setToolTipDuration(4)
        self.lineEdit_valueTP.setWhatsThis("")
        self.lineEdit_valueTP.setReadOnly(True)
        self.lineEdit_valueTP.setObjectName("lineEdit_valueTP")
        self.horizontalLayout_4.addWidget(self.lineEdit_valueTP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_valueFP = QtWidgets.QLineEdit(self.groupBox_Results)
        self.lineEdit_valueFP.setEnabled(True)
        self.lineEdit_valueFP.setReadOnly(True)
        self.lineEdit_valueFP.setObjectName("lineEdit_valueFP")
        self.horizontalLayout_5.addWidget(self.lineEdit_valueFP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_valueTN = QtWidgets.QLineEdit(self.groupBox_Results)
        self.lineEdit_valueTN.setEnabled(True)
        self.lineEdit_valueTN.setReadOnly(True)
        self.lineEdit_valueTN.setObjectName("lineEdit_valueTN")
        self.horizontalLayout_8.addWidget(self.lineEdit_valueTN)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_valueFN = QtWidgets.QLineEdit(self.groupBox_Results)
        self.lineEdit_valueFN.setEnabled(True)
        self.lineEdit_valueFN.setReadOnly(True)
        self.lineEdit_valueFN.setObjectName("lineEdit_valueFN")
        self.horizontalLayout_6.addWidget(self.lineEdit_valueFN)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_12 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_valueDSC = QtWidgets.QLineEdit(self.groupBox_Results)
        self.lineEdit_valueDSC.setEnabled(True)
        self.lineEdit_valueDSC.setReadOnly(True)
        self.lineEdit_valueDSC.setObjectName("lineEdit_valueDSC")
        self.horizontalLayout_7.addWidget(self.lineEdit_valueDSC)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.lineEdit_valueVS = QtWidgets.QLineEdit(self.groupBox_Results)
        self.lineEdit_valueVS.setEnabled(True)
        self.lineEdit_valueVS.setReadOnly(True)
        self.lineEdit_valueVS.setObjectName("lineEdit_valueVS")
        self.horizontalLayout_10.addWidget(self.lineEdit_valueVS)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.lineEdit_valueRI = QtWidgets.QLineEdit(self.groupBox_Results)
        self.lineEdit_valueRI.setEnabled(True)
        self.lineEdit_valueRI.setReadOnly(True)
        self.lineEdit_valueRI.setObjectName("lineEdit_valueRI")
        self.horizontalLayout_9.addWidget(self.lineEdit_valueRI)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.lineEdit_valueKAP = QtWidgets.QLineEdit(self.groupBox_Results)
        self.lineEdit_valueKAP.setEnabled(True)
        self.lineEdit_valueKAP.setReadOnly(True)
        self.lineEdit_valueKAP.setObjectName("lineEdit_valueKAP")
        self.horizontalLayout_11.addWidget(self.lineEdit_valueKAP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.lineEdit_valueAVD = QtWidgets.QLineEdit(self.groupBox_Results)
        self.lineEdit_valueAVD.setReadOnly(True)
        self.lineEdit_valueAVD.setObjectName("lineEdit_valueAVD")
        self.horizontalLayout_12.addWidget(self.lineEdit_valueAVD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.groupBox_Results)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.lineEdit_valueTPR = QtWidgets.QLineEdit(self.groupBox_Results)
        self.lineEdit_valueTPR.setReadOnly(True)
        self.lineEdit_valueTPR.setObjectName("lineEdit_valueTPR")
        self.horizontalLayout_13.addWidget(self.lineEdit_valueTPR)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.groupBox_Results)
        self.pushButton_Compare = QtWidgets.QPushButton(MainForm)
        self.pushButton_Compare.setObjectName("pushButton_Compare")
        self.verticalLayout.addWidget(self.pushButton_Compare)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("MainForm", "ROI to Compare"))
        self.label.setText(_translate("MainForm", "Ground Truth ROI"))
        self.label_3.setText(_translate("MainForm", "Save File:"))
        self.toolButton_OpenFileBrowser.setText(_translate("MainForm", "..."))
        self.groupBox_Results.setTitle(_translate("MainForm", "Results"))
        self.label_13.setText(_translate("MainForm", "Cardinalities:"))
        self.label_4.setText(_translate("MainForm", "TP"))
        self.label_5.setText(_translate("MainForm", "FP"))
        self.label_8.setText(_translate("MainForm", "TN"))
        self.label_6.setText(_translate("MainForm", "FN"))
        self.label_12.setText(_translate("MainForm", "Comparison Statistics:"))
        self.label_7.setText(_translate("MainForm", "DICE"))
        self.label_9.setText(_translate("MainForm", "VS"))
        self.label_10.setText(_translate("MainForm", "RI"))
        self.label_11.setText(_translate("MainForm", "KAP"))
        self.label_14.setText(_translate("MainForm", "AVD"))
        self.label_15.setText(_translate("MainForm", "TPR"))
        self.pushButton_Compare.setText(_translate("MainForm", "Compare"))

from ORSServiceClass.ORSWidget.orsobjectclasscombobox.orsobjectclasscombobox import OrsObjectClassComboBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainForm = QtWidgets.QWidget()
    ui = Ui_MainForm()
    ui.setupUi(MainForm)
    MainForm.show()
    sys.exit(app.exec_())

